version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - cron

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: mydb
      MYSQL_USER: user1
      MYSQL_PASSWORD: passwd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: passwd
    ports:
      - "8080:80"

  cron:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    entrypoint: [ "bash", "-c", "cron && tail -f /var/log/cron.log" ]
    depends_on:
      - db

volumes:
  db_data:
